/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiCronSocialPublishRouteImport } from './routes/api/cron/social-publish'
import { Route as ApiSocialYoutubeOauthStartRouteImport } from './routes/api/social/youtube/oauth/start'
import { Route as ApiSocialYoutubeOauthCallbackRouteImport } from './routes/api/social/youtube/oauth/callback'
import { Route as ApiSocialNaverOauthStartRouteImport } from './routes/api/social/naver/oauth/start'
import { Route as ApiSocialNaverOauthCallbackRouteImport } from './routes/api/social/naver/oauth/callback'
import { Route as ApiSocialMetaOauthStartRouteImport } from './routes/api/social/meta/oauth/start'
import { Route as ApiSocialMetaOauthCallbackRouteImport } from './routes/api/social/meta/oauth/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCronSocialPublishRoute = ApiCronSocialPublishRouteImport.update({
  id: '/api/cron/social-publish',
  path: '/api/cron/social-publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialYoutubeOauthStartRoute =
  ApiSocialYoutubeOauthStartRouteImport.update({
    id: '/api/social/youtube/oauth/start',
    path: '/api/social/youtube/oauth/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSocialYoutubeOauthCallbackRoute =
  ApiSocialYoutubeOauthCallbackRouteImport.update({
    id: '/api/social/youtube/oauth/callback',
    path: '/api/social/youtube/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSocialNaverOauthStartRoute =
  ApiSocialNaverOauthStartRouteImport.update({
    id: '/api/social/naver/oauth/start',
    path: '/api/social/naver/oauth/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSocialNaverOauthCallbackRoute =
  ApiSocialNaverOauthCallbackRouteImport.update({
    id: '/api/social/naver/oauth/callback',
    path: '/api/social/naver/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSocialMetaOauthStartRoute = ApiSocialMetaOauthStartRouteImport.update({
  id: '/api/social/meta/oauth/start',
  path: '/api/social/meta/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialMetaOauthCallbackRoute =
  ApiSocialMetaOauthCallbackRouteImport.update({
    id: '/api/social/meta/oauth/callback',
    path: '/api/social/meta/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/cron/social-publish': typeof ApiCronSocialPublishRoute
  '/api/social/meta/oauth/callback': typeof ApiSocialMetaOauthCallbackRoute
  '/api/social/meta/oauth/start': typeof ApiSocialMetaOauthStartRoute
  '/api/social/naver/oauth/callback': typeof ApiSocialNaverOauthCallbackRoute
  '/api/social/naver/oauth/start': typeof ApiSocialNaverOauthStartRoute
  '/api/social/youtube/oauth/callback': typeof ApiSocialYoutubeOauthCallbackRoute
  '/api/social/youtube/oauth/start': typeof ApiSocialYoutubeOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/cron/social-publish': typeof ApiCronSocialPublishRoute
  '/api/social/meta/oauth/callback': typeof ApiSocialMetaOauthCallbackRoute
  '/api/social/meta/oauth/start': typeof ApiSocialMetaOauthStartRoute
  '/api/social/naver/oauth/callback': typeof ApiSocialNaverOauthCallbackRoute
  '/api/social/naver/oauth/start': typeof ApiSocialNaverOauthStartRoute
  '/api/social/youtube/oauth/callback': typeof ApiSocialYoutubeOauthCallbackRoute
  '/api/social/youtube/oauth/start': typeof ApiSocialYoutubeOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/cron/social-publish': typeof ApiCronSocialPublishRoute
  '/api/social/meta/oauth/callback': typeof ApiSocialMetaOauthCallbackRoute
  '/api/social/meta/oauth/start': typeof ApiSocialMetaOauthStartRoute
  '/api/social/naver/oauth/callback': typeof ApiSocialNaverOauthCallbackRoute
  '/api/social/naver/oauth/start': typeof ApiSocialNaverOauthStartRoute
  '/api/social/youtube/oauth/callback': typeof ApiSocialYoutubeOauthCallbackRoute
  '/api/social/youtube/oauth/start': typeof ApiSocialYoutubeOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/api/generate-image'
    | '/api/cron/social-publish'
    | '/api/social/meta/oauth/callback'
    | '/api/social/meta/oauth/start'
    | '/api/social/naver/oauth/callback'
    | '/api/social/naver/oauth/start'
    | '/api/social/youtube/oauth/callback'
    | '/api/social/youtube/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/api/generate-image'
    | '/api/cron/social-publish'
    | '/api/social/meta/oauth/callback'
    | '/api/social/meta/oauth/start'
    | '/api/social/naver/oauth/callback'
    | '/api/social/naver/oauth/start'
    | '/api/social/youtube/oauth/callback'
    | '/api/social/youtube/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/api/generate-image'
    | '/api/cron/social-publish'
    | '/api/social/meta/oauth/callback'
    | '/api/social/meta/oauth/start'
    | '/api/social/naver/oauth/callback'
    | '/api/social/naver/oauth/start'
    | '/api/social/youtube/oauth/callback'
    | '/api/social/youtube/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiCronSocialPublishRoute: typeof ApiCronSocialPublishRoute
  ApiSocialMetaOauthCallbackRoute: typeof ApiSocialMetaOauthCallbackRoute
  ApiSocialMetaOauthStartRoute: typeof ApiSocialMetaOauthStartRoute
  ApiSocialNaverOauthCallbackRoute: typeof ApiSocialNaverOauthCallbackRoute
  ApiSocialNaverOauthStartRoute: typeof ApiSocialNaverOauthStartRoute
  ApiSocialYoutubeOauthCallbackRoute: typeof ApiSocialYoutubeOauthCallbackRoute
  ApiSocialYoutubeOauthStartRoute: typeof ApiSocialYoutubeOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cron/social-publish': {
      id: '/api/cron/social-publish'
      path: '/api/cron/social-publish'
      fullPath: '/api/cron/social-publish'
      preLoaderRoute: typeof ApiCronSocialPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social/youtube/oauth/start': {
      id: '/api/social/youtube/oauth/start'
      path: '/api/social/youtube/oauth/start'
      fullPath: '/api/social/youtube/oauth/start'
      preLoaderRoute: typeof ApiSocialYoutubeOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social/youtube/oauth/callback': {
      id: '/api/social/youtube/oauth/callback'
      path: '/api/social/youtube/oauth/callback'
      fullPath: '/api/social/youtube/oauth/callback'
      preLoaderRoute: typeof ApiSocialYoutubeOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social/naver/oauth/start': {
      id: '/api/social/naver/oauth/start'
      path: '/api/social/naver/oauth/start'
      fullPath: '/api/social/naver/oauth/start'
      preLoaderRoute: typeof ApiSocialNaverOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social/naver/oauth/callback': {
      id: '/api/social/naver/oauth/callback'
      path: '/api/social/naver/oauth/callback'
      fullPath: '/api/social/naver/oauth/callback'
      preLoaderRoute: typeof ApiSocialNaverOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social/meta/oauth/start': {
      id: '/api/social/meta/oauth/start'
      path: '/api/social/meta/oauth/start'
      fullPath: '/api/social/meta/oauth/start'
      preLoaderRoute: typeof ApiSocialMetaOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social/meta/oauth/callback': {
      id: '/api/social/meta/oauth/callback'
      path: '/api/social/meta/oauth/callback'
      fullPath: '/api/social/meta/oauth/callback'
      preLoaderRoute: typeof ApiSocialMetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiCronSocialPublishRoute: ApiCronSocialPublishRoute,
  ApiSocialMetaOauthCallbackRoute: ApiSocialMetaOauthCallbackRoute,
  ApiSocialMetaOauthStartRoute: ApiSocialMetaOauthStartRoute,
  ApiSocialNaverOauthCallbackRoute: ApiSocialNaverOauthCallbackRoute,
  ApiSocialNaverOauthStartRoute: ApiSocialNaverOauthStartRoute,
  ApiSocialYoutubeOauthCallbackRoute: ApiSocialYoutubeOauthCallbackRoute,
  ApiSocialYoutubeOauthStartRoute: ApiSocialYoutubeOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
